// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9aToQdkpjTiO_DZDu6SySFy4svNuTLs0',
    appId: '1:26629335757:web:2741947da4d2784d3f5784',
    messagingSenderId: '26629335757',
    projectId: 'eslam-23',
    authDomain: 'eslam-23.firebaseapp.com',
    databaseURL: 'https://eslam-23-default-rtdb.firebaseio.com',
    storageBucket: 'eslam-23.appspot.com',
    measurementId: 'G-MLTR83PV1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVcUREfrJ7pnUUaqGgWqOLVSCv1CWX6Q4',
    appId: '1:26629335757:android:8e978737dcdb97ad3f5784',
    messagingSenderId: '26629335757',
    projectId: 'eslam-23',
    databaseURL: 'https://eslam-23-default-rtdb.firebaseio.com',
    storageBucket: 'eslam-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ejIkGxvE5As0KWGsmkz2dtNbDvhgoKE',
    appId: '1:26629335757:ios:709d88b556e106273f5784',
    messagingSenderId: '26629335757',
    projectId: 'eslam-23',
    databaseURL: 'https://eslam-23-default-rtdb.firebaseio.com',
    storageBucket: 'eslam-23.appspot.com',
    iosClientId: '26629335757-6h666s8g3o60t9c94g2amm6ap8a1m4ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.nova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ejIkGxvE5As0KWGsmkz2dtNbDvhgoKE',
    appId: '1:26629335757:ios:709d88b556e106273f5784',
    messagingSenderId: '26629335757',
    projectId: 'eslam-23',
    databaseURL: 'https://eslam-23-default-rtdb.firebaseio.com',
    storageBucket: 'eslam-23.appspot.com',
    iosClientId: '26629335757-6h666s8g3o60t9c94g2amm6ap8a1m4ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.nova',
  );
}
