// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrpH8DcLs_UixGA5iAn5A2mOyb-cmYD4U',
    appId: '1:936102801906:web:9f7e5ad25947327f367b6b',
    messagingSenderId: '936102801906',
    projectId: 'nova-7bc8e',
    authDomain: 'nova-7bc8e.firebaseapp.com',
    databaseURL: 'https://nova-7bc8e-default-rtdb.firebaseio.com',
    storageBucket: 'nova-7bc8e.appspot.com',
    measurementId: 'G-36KGGBH2CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZEpJrTCtsa1XNC4MGoGumKOD6O39ZB3Y',
    appId: '1:936102801906:android:48be759b223d8acb367b6b',
    messagingSenderId: '936102801906',
    projectId: 'nova-7bc8e',
    databaseURL: 'https://nova-7bc8e-default-rtdb.firebaseio.com',
    storageBucket: 'nova-7bc8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMCWdqPyM4uLUgUPzrsjIQzVEi3mYZN_g',
    appId: '1:936102801906:ios:ffe0326039e230ac367b6b',
    messagingSenderId: '936102801906',
    projectId: 'nova-7bc8e',
    databaseURL: 'https://nova-7bc8e-default-rtdb.firebaseio.com',
    storageBucket: 'nova-7bc8e.appspot.com',
    iosClientId: '936102801906-csnhpfcfjkf08le03q8srm0she4c1m8r.apps.googleusercontent.com',
    iosBundleId: 'com.mohamedsayed.nova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMCWdqPyM4uLUgUPzrsjIQzVEi3mYZN_g',
    appId: '1:936102801906:ios:ffe0326039e230ac367b6b',
    messagingSenderId: '936102801906',
    projectId: 'nova-7bc8e',
    databaseURL: 'https://nova-7bc8e-default-rtdb.firebaseio.com',
    storageBucket: 'nova-7bc8e.appspot.com',
    iosClientId: '936102801906-csnhpfcfjkf08le03q8srm0she4c1m8r.apps.googleusercontent.com',
    iosBundleId: 'com.mohamedsayed.nova',
  );
}
